### ISSUE TITLE
Crash in matchtemplate.js crashes Docker service

### ISSUE THREAD

**Issue by Ekliptor** [xudafeng/nodecv#9]
If I upload to 2 completely different images to the docker webservice, the nodejs webserver crashes and the whole docker container stops with the following error:

```
TypeError: Cannot read property '1' of null
 at nodecv.matchTemplate (/nodecv-server/lib/controllers/matchtemplate.js:17:34)
 at /nodecv-server/lib/controllers/matchtemplate.js:16:16
 at /nodecv-server/lib/controllers/matchtemplate.js:15:14
 at resolve (/nodecv-server/lib/controllers/matchtemplate.js:14:12)
 at handle (/nodecv-server/lib/controllers/matchtemplate.js:9:10)
 at Object.module.exports (/nodecv-server/lib/controllers/matchtemplate.js:31:25)
 at next (native)
 at onFulfilled (/nodecv-server/node_modules/co/index.js:65:19)
 at /nodecv-server/node_modules/co/index.js:54:5
 at Object.co (/nodecv-server/node_modules/co/index.js:50:10
```

The issue is that the try catch block in the HTTP handler only catches synchronous calls. The callback functions have another stack. Suggested fix, a 2nd try-catch inside the callback functions:
```
    nodecv.imread(image1path, function(err, image1) {
      nodecv.imread(image2path, function(err, image2) {
      nodecv.matchTemplate(image1, image2, 5, (error, match) => {
        try {
      
                image1.rectangle([match[1], match[2]], [match[3], match[4]], color, 1);
                nodecv.imwrite(outputPath, image1);
                resolve(match);
            });
        }
        catch (err) {
          console.error("Match pattern error", err);
          resolve([{err: "no match"}, 0, 0, 0, 0]); // a valid result looks like: [{},1110,721,282,112]
        }
      });
    });
  });
```
Alternatively you can validate the arrays before accessing elements inside it.

```
         nodecv.matchTemplate(image1, image2, 5, (error, match) => {
              if (match == null || Array.isArray(match) === false || match.length < 5)
                return resolve([{err: "no match"}, 0, 0, 0, 0]); // a valid result looks like: [{},1110,721,282,112]
```

**Comment by Ekliptor** [comment]
My manual 2nd fix, checking for the value of match explicitly seems more elegant than the try-catch idea
